/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthenticationResponse { 
    userRole?: AuthenticationResponse.UserRoleEnum;
    userId?: number;
    jwt?: string;
}
export namespace AuthenticationResponse {
    export type UserRoleEnum = 'ADMIN' | 'CUSTOMER';
    export const UserRoleEnum = {
        Admin: 'ADMIN' as UserRoleEnum,
        Customer: 'CUSTOMER' as UserRoleEnum
    };
}


